#!/bin/bash

if grep -q root /etc/passwd;
then
	echo "root is in the password file"
else 
	echo "root is missing from the password file"
fi


if [ 1 -eq 2 ]; then 
	echo "1 is equal to 2"
else
	echo "1 is not equal to 2"
fi

if ! [ 12 -ne 20 ]; then
	echo "12 is not equal to 20."
else
	echo "12 is equal to 20."
fi


if [ "a" = "a" ]; then 
	echo "\"a\" is equal to \"a\"."
else
	echo "\"a\" is not equal to \"a\"."
fi


test 1 -eq 1 -o 2 -eq 2
echo $?
